# Generated by Django 4.2.5 on 2023-10-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_producttransaction_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='with_serial',
            field=models.BooleanField(default=False),
        ),
    ]
