# Generated by Django 4.2.5 on 2023-10-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_supplier_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='serials',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='serials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier'),
        ),
    ]
