# Generated by Django 4.2.5 on 2023-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_repairstatus_repairtype_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_added_recently',
            field=models.BooleanField(default=False),
        ),
    ]
