# Generated by Django 4.2.5 on 2023-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_pettycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
