# Generated by Django 4.2.5 on 2023-12-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_pettycash_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
