# Generated by Django 4.2.5 on 2024-05-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_image_remove_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_in_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
